### ISSUE TITLE
Problem with Intl

### ISSUE THREAD

**Issue by OleksandrDiachenko** [abobija/loggerx#1]
Hey! Can we find the easy issue of this problem? :)

`  loggerx: ^1.3.6
  esp_smartconfig: ^1.1.11
  easy_localization: ^3.0.1`

Because no versions of loggerx match >1.3.6 <2.0.0 and loggerx 1.3.6 depends on intl ^0.18.0, loggerx ^1.3.6 requires intl ^0.18.0.
And because easy_localization >=3.0.0 depends on intl >=0.17.0-nullsafety <=0.17.0, loggerx ^1.3.6 is incompatible with easy_localization >=3.0.0.
So, because smart_connect depends on both loggerx ^1.3.6 and easy_localization ^3.0.1, version solving failed.
pub get failed (1; So, because smart_connect depends on both loggerx ^1.3.6 and easy_localization ^3.0.1, version solving failed.)
exit code 1

**Comment by abobija** [comment]
You can ask maintainers of the `easy_localization` package to update `intl` package to `^0.18.0`.

But for now, you can use older version `1.1.10` of the package `esp_smartconfig`. To do that you can manually open your `pubspec.yaml` file and add next package:

`esp_smartconfig: ^1.1.10`

**Comment by OleksandrDiachenko** [comment]
It was too easy! 
Thank you!
